---
abstract: 'a transcription markup syntax for TEI XML'
author:
  - 'Tara L Andrews <aurum@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Text::TEI::Markup
name: Text-TEI-Markup
no_index:
  directory:
    - inc
    - t
requires:
  XML::LibXML: 0
  perl: 5.008003
version: 1.0
