---
abstract: 'a variation on Text::WagnerFischer for Armenian-language strings'
author:
  - 'Tara L Andrews <aurum@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Text::WagnerFischer::Armenian
name: Text-WagnerFischer-Armenian
no_index:
  directory:
    - inc
    - t
requires:
  Text::WagnerFischer: 0
  perl: 5.008003
version: 0.03
